package: api
generate:
  gin-server: true
  strict-server: true
  models: true
  embedded-spec: true
output-options:
  skip-prune: true
  exclude-tags:
    - sse-manual
    - proxy-manual
output: server.gen.go
